apiVersion: v1
kind: Pod
metadata:
  name: nginx-giropops
  labels:
    run: nginx-giropops
    app: giropops-strigus
spec:
  containers:
  - image: nginx
    name: nginx-giropops
    ports:
    - containerPort: 80
    resources: 
      limits: 
        cpu: "0.5"
        memory: "256Mi"
      requests:
        cpu: "0.3"
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always